router_bgp:
  as: '65316'
  router_id: 10.3.103.128
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '65316'
      next_hop_self: true
      description: DC3-BORDER1
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      send_community: all
      maximum_routes: 0
      ebgp_multihop: 3
    WAN:
      send_community: all
      maximum_routes: 100000
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  neighbors:
    10.255.254.252:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: DC3-BORDER1
    10.3.1.252:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65003'
      description: DC3-SPINE1_Ethernet8/1
    10.3.1.254:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65003'
      description: DC3-SPINE2_Ethernet8/1
    10.3.100.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC3-SPINE1
      remote_as: '65003'
    10.3.100.2:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC3-SPINE2
      remote_as: '65003'
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  vrfs:
    CORP:
      router_id: 10.3.103.128
      rd: 10.3.103.128:10
      route_targets:
        import:
          evpn:
          - '10:10'
        export:
          evpn:
          - '10:10'
      redistribute_routes:
      - connected
      neighbors:
        10.255.254.252:
          peer_group: MLAG-IPv4-UNDERLAY-PEER
        33.33.33.5:
          peer_group: WAN
          remote_as: 22222
      address_families:
        ipv4:
          neighbors:
            33.33.33.5:
              activate: true
  vlans:
    10:
      tenant: CORP
      rd: 10.3.103.128:10010
      route_targets:
        both:
        - 10010:10010
      redistribute_routes:
      - learned
    40:
      tenant: CORP
      rd: 10.3.103.128:10040
      route_targets:
        both:
        - 10040:10040
      redistribute_routes:
      - learned
static_routes:
- vrf: management
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.99.99.1
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - apiserver.arista.io:443
  cvauth:
    method: token-secure
    token_file: /mnt/flash/cv-onboarding-token
  cvvrf: management
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: management
  nodes:
  - 1.1.1.1
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: '32768'
  no_spanning_tree_vlan: 4093-4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$cObeccKViX0iyttR$A.3Pb7XxO15mEowsBC8fUjcrt3E77viyGgoWroBJ6jh0ZppqqMhVHpR2xyDBxOOIJD0aXh.mYpZjz5F88rbR.0
  dcapetz:
    privilege: 15
    role: network-admin
    sha512_password: $6$MmPwehEOaBQNSZCO$eAg4JPnxxyqKVqVNYak76EoYiCjaJAFQVQSFVXqTzBKcA57ZbYpJt/1lIFtVwGOpnD4/OgSHMxfmyWIhbq7bB/
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZ148VUrWGE12gbl/yuMn2tCKwaJTmayGqEZGseVCtWO54gB0J2vt/m75xY5dmHquZvLQVfgp7JfV/FUa+Ao+QhHFFxdq7Br+T8PBE8u64Mr97MWpUT3Kc79lL48MvJfNH/adQ8sRK2LkLDp2Lgfc8XQNsA28NkOOh0EV4iSWVCv9K0m19Hihp6cjfvAb8Jt9y5NvtZiJvsBmv+A6DJ5okEsmQ3qVgmEzJ2xWHigYwZOmJsW5XcS0+cqVVT28J/rE4d6QPds6kSx9gkp3/RJxxH9lwhzDQFoOmfMlz5TixG7a4cnvvxETmEfw+QKYcKcIbCZdTi8/1+FLLQ2SOVQlVFsbzRcfUa3Z+FfYk358H6AYQ5fY2R7pYHC8jIOjVyp4Q0KcCo29NzZ07eXr6Z0hmaB7cXTP2devB6VqPxnhLeBXIPgLs8JU/yJd7aneYEonn5vSnEBiC3E61l8Dx3pz0WBYsZHNfL+A/stCBdJRl35XAoGqnEfU73eaZiXx46CU=
      dcapetz@dcapetz
clock:
  timezone: US/Central
vrfs:
  management:
    ip_routing: false
  CORP:
    tenant: CORP
    ip_routing: true
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: management
    ip_address: 10.99.99.220/24
    gateway: 10.99.99.1
    type: oob
mac_address_table:
  aging_time: 1300
management_api_http:
  enable_vrfs:
    management: {}
  enable_https: true
vlans:
  4093:
    tenant: system
    name: LEAF_PEER_L3
    trunk_groups:
    - LEAF_PEER_L3
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
  10:
    tenant: CORP
    name: CORP_GLOBAL
  40:
    tenant: CORP
    name: CORP_DC3
  3009:
    tenant: CORP
    name: MLAG_iBGP_CORP
    trunk_groups:
    - LEAF_PEER_L3
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    shutdown: false
    mtu: 1500
    ip_address: 10.255.254.253/31
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 10.255.255.253/31
    no_autostate: true
    mtu: 1500
  Vlan10:
    tenant: CORP
    tags:
    - compute
    - border
    description: CORP_GLOBAL
    shutdown: false
    ip_address_virtual: 10.10.10.1/24
    vrf: CORP
  Vlan40:
    tenant: CORP
    tags:
    - compute
    - border
    description: CORP_DC3
    shutdown: false
    ip_address_virtual: 10.40.40.1/24
    vrf: CORP
  Vlan3009:
    tenant: CORP
    type: underlay_peering
    shutdown: false
    description: 'MLAG_PEER_L3_iBGP: vrf CORP'
    vrf: CORP
    mtu: 1500
    ip_address: 10.255.254.253/31
port_channel_interfaces:
  Port-Channel551:
    description: MLAG_PEER_DC3-BORDER1_Po551
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
ethernet_interfaces:
  Ethernet55/1:
    peer: DC3-BORDER1
    peer_interface: Ethernet55/1
    peer_type: mlag_peer
    description: MLAG_PEER_DC3-BORDER1_Ethernet55/1
    type: switched
    shutdown: false
    channel_group:
      id: 551
      mode: active
  Ethernet56/1:
    peer: DC3-BORDER1
    peer_interface: Ethernet56/1
    peer_type: mlag_peer
    description: MLAG_PEER_DC3-BORDER1_Ethernet56/1
    type: switched
    shutdown: false
    channel_group:
      id: 551
      mode: active
  Ethernet49/1:
    peer: DC3-SPINE1
    peer_interface: Ethernet8/1
    peer_type: spine
    description: P2P_LINK_TO_DC3-SPINE1_Ethernet8/1
    shutdown: false
    mtu: 1500
    type: routed
    ip_address: 10.3.1.253/31
  Ethernet50/1:
    peer: DC3-SPINE2
    peer_interface: Ethernet8/1
    peer_type: spine
    description: P2P_LINK_TO_DC3-SPINE2_Ethernet8/1
    shutdown: false
    mtu: 1500
    type: routed
    ip_address: 10.3.1.255/31
  Ethernet1:
    peer_type: l3_interface
    ip_address: 33.33.33.6/30
    shutdown: false
    description: L3 Uplink to WAN for CORP VRF
    type: routed
    vrf: CORP
mlag_configuration:
  domain_id: DC3_BORDER_LEAFS
  local_interface: Vlan4094
  peer_address: 10.255.255.252
  peer_link: Port-Channel551
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.3.103.128/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 10.3.113.127/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.3.103.0/24 eq 32
      20:
        action: permit 10.3.113.0/24 eq 32
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:00:99
vxlan_interface:
  Vxlan1:
    description: DC3-BORDER2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
        10:
          vni: 10010
        40:
          vni: 10040
      vrfs:
        CORP:
          vni: 10
