router_bgp:
  as: '65116'
  router_id: 10.1.101.32
  bgp_defaults:
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65116'
    next_hop_self: true
    description: ENT-DC1-EDGE1
    maximum_routes: 12000
    send_community: all
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
  - name: EVPN-OVERLAY-CORE
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 15
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
    - name: EVPN-OVERLAY-CORE
      activate: false
  neighbors:
  - ip_address: 10.255.251.60
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    description: ENT-DC1-EDGE1
  - ip_address: 10.1.0.124
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    description: ENT-DC1-SPINE1_Ethernet8/1
  - ip_address: 10.1.0.126
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    description: ENT-DC1-SPINE2_Ethernet8/1
  - ip_address: 10.1.100.1
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC1-SPINE1
    remote_as: '65100'
  - ip_address: 10.1.100.2
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC1-SPINE2
    remote_as: '65100'
  - ip_address: 10.2.101.31
    peer_group: EVPN-OVERLAY-CORE
    description: ENT-DC2-EDGE1
    remote_as: '65216'
  - ip_address: 10.2.101.32
    peer_group: EVPN-OVERLAY-CORE
    description: ENT-DC2-EDGE2
    remote_as: '65216'
  - ip_address: 10.0.11.2
    remote_as: '64991'
    description: ENT-DC1-CORE1
    peer_group: IPv4-UNDERLAY-PEERS
  - ip_address: 10.0.12.2
    remote_as: '64991'
    description: ENT-DC1-CORE2
    peer_group: IPv4-UNDERLAY-PEERS
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  address_family_evpn:
    neighbor_default:
      next_hop_self_received_evpn_routes:
        enable: true
        inter_domain: true
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-CORE
      domain_remote: true
      activate: true
  vrfs:
  - name: CORP
    router_id: 10.1.101.32
    rd: 10.1.101.32:10
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '10:10'
      export:
      - address_family: evpn
        route_targets:
        - '10:10'
    redistribute_routes:
    - source_protocol: connected
    neighbors:
    - ip_address: 10.255.251.60
      peer_group: MLAG-IPv4-UNDERLAY-PEER
  vlans:
  - id: 10
    tenant: CORP
    rd: 10.1.101.32:10010
    route_targets:
      both:
      - 10010:10010
      import_export_evpn_domains:
      - domain: remote
        route_target: 10010:10010
    redistribute_routes:
    - learned
    rd_evpn_domain:
      domain: remote
      rd: 10.1.101.32:10010
  - id: 20
    tenant: CORP
    rd: 10.1.101.32:10020
    route_targets:
      both:
      - 10020:10020
      import_export_evpn_domains:
      - domain: remote
        route_target: 10020:10020
    redistribute_routes:
    - learned
    rd_evpn_domain:
      domain: remote
      rd: 10.1.101.32:10020
static_routes:
- vrf: management
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.99.99.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: management
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
  no_spanning_tree_vlan: 4093-4094
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$cObeccKViX0iyttR$A.3Pb7XxO15mEowsBC8fUjcrt3E77viyGgoWroBJ6jh0ZppqqMhVHpR2xyDBxOOIJD0aXh.mYpZjz5F88rbR.0
- name: dcapetz
  privilege: 15
  role: network-admin
  sha512_password: $6$MmPwehEOaBQNSZCO$eAg4JPnxxyqKVqVNYak76EoYiCjaJAFQVQSFVXqTzBKcA57ZbYpJt/1lIFtVwGOpnD4/OgSHMxfmyWIhbq7bB/
  ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZ148VUrWGE12gbl/yuMn2tCKwaJTmayGqEZGseVCtWO54gB0J2vt/m75xY5dmHquZvLQVfgp7JfV/FUa+Ao+QhHFFxdq7Br+T8PBE8u64Mr97MWpUT3Kc79lL48MvJfNH/adQ8sRK2LkLDp2Lgfc8XQNsA28NkOOh0EV4iSWVCv9K0m19Hihp6cjfvAb8Jt9y5NvtZiJvsBmv+A6DJ5okEsmQ3qVgmEzJ2xWHigYwZOmJsW5XcS0+cqVVT28J/rE4d6QPds6kSx9gkp3/RJxxH9lwhzDQFoOmfMlz5TixG7a4cnvvxETmEfw+QKYcKcIbCZdTi8/1+FLLQ2SOVQlVFsbzRcfUa3Z+FfYk358H6AYQ5fY2R7pYHC8jIOjVyp4Q0KcCo29NzZ07eXr6Z0hmaB7cXTP2devB6VqPxnhLeBXIPgLs8JU/yJd7aneYEonn5vSnEBiC3E61l8Dx3pz0WBYsZHNfL+A/stCBdJRl35XAoGqnEfU73eaZiXx46CU=
    dcapetz@dcapetz
clock:
  timezone: US/Central
vrfs:
- name: management
  ip_routing: false
- name: CORP
  tenant: CORP
  ip_routing: true
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: management
  ip_address: 10.99.99.56/24
  gateway: 10.99.99.1
  type: oob
mac_address_table:
  aging_time: 1300
management_api_http:
  enable_vrfs:
  - name: management
  enable_https: true
vlans:
- id: 4093
  tenant: system
  name: LEAF_PEER_L3
  trunk_groups:
  - LEAF_PEER_L3
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
- id: 10
  name: CORP_GLOBAL_SHARED_10
  tenant: CORP
- id: 20
  name: CORP_GLOBAL_SHARED_20
  tenant: CORP
- id: 3009
  name: MLAG_iBGP_CORP
  trunk_groups:
  - LEAF_PEER_L3
  tenant: CORP
vlan_interfaces:
- name: Vlan4093
  description: MLAG_PEER_L3_PEERING
  shutdown: false
  mtu: 1500
  ip_address: 10.255.251.61/31
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 10.255.255.61/31
  no_autostate: true
  mtu: 1500
- name: Vlan10
  tenant: CORP
  tags:
  - GLOBAL_LEAVES
  description: CORP_GLOBAL_SHARED_10
  shutdown: false
  ip_address_virtual: 10.10.10.1/24
  vrf: CORP
- name: Vlan20
  tenant: CORP
  tags:
  - GLOBAL_LEAVES
  description: CORP_GLOBAL_SHARED_20
  shutdown: false
  ip_address_virtual: 10.20.20.1/24
  vrf: CORP
- name: Vlan3009
  tenant: CORP
  type: underlay_peering
  shutdown: false
  description: 'MLAG_PEER_L3_iBGP: vrf CORP'
  vrf: CORP
  mtu: 1500
  ip_address: 10.255.251.61/31
port_channel_interfaces:
- name: Port-Channel551
  description: MLAG_PEER_ENT-DC1-EDGE1_Po551
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - LEAF_PEER_L3
  - MLAG
ethernet_interfaces:
- name: Ethernet55/1
  peer: ENT-DC1-EDGE1
  peer_interface: Ethernet55/1
  peer_type: mlag_peer
  description: MLAG_PEER_ENT-DC1-EDGE1_Ethernet55/1
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 551
    mode: active
- name: Ethernet56/1
  peer: ENT-DC1-EDGE1
  peer_interface: Ethernet56/1
  peer_type: mlag_peer
  description: MLAG_PEER_ENT-DC1-EDGE1_Ethernet56/1
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 551
    mode: active
- name: Ethernet49/1
  peer: ENT-DC1-SPINE1
  peer_interface: Ethernet8/1
  peer_type: spine
  description: P2P_LINK_TO_ENT-DC1-SPINE1_Ethernet8/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.1.0.125/31
- name: Ethernet50/1
  peer: ENT-DC1-SPINE2
  peer_interface: Ethernet8/1
  peer_type: spine
  description: P2P_LINK_TO_ENT-DC1-SPINE2_Ethernet8/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.1.0.127/31
- name: Ethernet51/1
  peer: ENT-DC1-CORE1
  peer_interface: Ethernet52/1
  peer_type: other
  description: P2P_LINK_TO_ENT-DC1-CORE1_Ethernet52/1
  type: routed
  shutdown: false
  mtu: 9214
  eos_cli: sflow enable
  ip_address: 10.0.11.3/31
- name: Ethernet52/1
  peer: ENT-DC1-CORE2
  peer_interface: Ethernet52/1
  peer_type: other
  description: P2P_LINK_TO_ENT-DC1-CORE2_Ethernet52/1
  type: routed
  shutdown: false
  mtu: 9214
  eos_cli: sflow enable
  ip_address: 10.0.12.3/31
mlag_configuration:
  domain_id: EnterpriseDC1EdgeLeaves
  local_interface: Vlan4094
  peer_address: 10.255.255.60
  peer_link: Port-Channel551
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - origin incomplete
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 10.1.101.32/32
- name: Loopback1
  description: VTEP_VXLAN_Tunnel_Source
  shutdown: false
  ip_address: 10.1.102.31/32
- name: Loopback10
  description: CORP_VTEP_DIAGNOSTICS
  shutdown: false
  vrf: CORP
  ip_address: 10.255.10.32/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.1.101.0/24 eq 32
  - sequence: 20
    action: permit 10.1.102.0/24 eq 32
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:00:01
vxlan_interface:
  Vxlan1:
    description: ENT-DC1-EDGE2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 10
        vni: 10010
      - id: 20
        vni: 10020
      vrfs:
      - name: CORP
        vni: 10
virtual_source_nat_vrfs:
- name: CORP
  ip_address: 10.255.10.32
