router_bgp:
  as: '65200'
  router_id: 10.2.100.1
  bgp_defaults:
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
    next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  neighbors:
  - ip_address: 10.2.0.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65201'
    description: ENT-DC2-LEAF1_Ethernet49/1
  - ip_address: 10.2.0.5
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65201'
    description: ENT-DC2-LEAF2_Ethernet49/1
  - ip_address: 10.2.0.9
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65202'
    description: ENT-DC2-LEAF3_Ethernet49/1
  - ip_address: 10.2.0.13
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65202'
    description: ENT-DC2-LEAF4_Ethernet49/1
  - ip_address: 10.2.0.17
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65203'
    description: ENT-DC2-LEAF5_Ethernet49/1
  - ip_address: 10.2.0.21
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65203'
    description: ENT-DC2-LEAF6_Ethernet49/1
  - ip_address: 10.2.0.121
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65216'
    description: ENT-DC2-BORDER1_Ethernet49/1
  - ip_address: 10.2.0.125
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65216'
    description: ENT-DC2-BORDER2_Ethernet49/1
  - ip_address: 10.2.101.31
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-BORDER1
    remote_as: '65216'
  - ip_address: 10.2.101.32
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-BORDER2
    remote_as: '65216'
  - ip_address: 10.2.101.1
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF1
    remote_as: '65201'
  - ip_address: 10.2.101.2
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF2
    remote_as: '65201'
  - ip_address: 10.2.101.3
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF3
    remote_as: '65202'
  - ip_address: 10.2.101.4
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF4
    remote_as: '65202'
  - ip_address: 10.2.101.5
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF5
    remote_as: '65203'
  - ip_address: 10.2.101.6
    peer_group: EVPN-OVERLAY-PEERS
    description: ENT-DC2-LEAF6
    remote_as: '65203'
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
static_routes:
- vrf: management
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.99.99.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: management
spanning_tree:
  mode: none
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$cObeccKViX0iyttR$A.3Pb7XxO15mEowsBC8fUjcrt3E77viyGgoWroBJ6jh0ZppqqMhVHpR2xyDBxOOIJD0aXh.mYpZjz5F88rbR.0
- name: dcapetz
  privilege: 15
  role: network-admin
  sha512_password: $6$MmPwehEOaBQNSZCO$eAg4JPnxxyqKVqVNYak76EoYiCjaJAFQVQSFVXqTzBKcA57ZbYpJt/1lIFtVwGOpnD4/OgSHMxfmyWIhbq7bB/
  ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZ148VUrWGE12gbl/yuMn2tCKwaJTmayGqEZGseVCtWO54gB0J2vt/m75xY5dmHquZvLQVfgp7JfV/FUa+Ao+QhHFFxdq7Br+T8PBE8u64Mr97MWpUT3Kc79lL48MvJfNH/adQ8sRK2LkLDp2Lgfc8XQNsA28NkOOh0EV4iSWVCv9K0m19Hihp6cjfvAb8Jt9y5NvtZiJvsBmv+A6DJ5okEsmQ3qVgmEzJ2xWHigYwZOmJsW5XcS0+cqVVT28J/rE4d6QPds6kSx9gkp3/RJxxH9lwhzDQFoOmfMlz5TixG7a4cnvvxETmEfw+QKYcKcIbCZdTi8/1+FLLQ2SOVQlVFsbzRcfUa3Z+FfYk358H6AYQ5fY2R7pYHC8jIOjVyp4Q0KcCo29NzZ07eXr6Z0hmaB7cXTP2devB6VqPxnhLeBXIPgLs8JU/yJd7aneYEonn5vSnEBiC3E61l8Dx3pz0WBYsZHNfL+A/stCBdJRl35XAoGqnEfU73eaZiXx46CU=
    dcapetz@dcapetz
clock:
  timezone: US/Central
vrfs:
- name: management
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: management
  ip_address: 10.99.99.41/24
  gateway: 10.99.99.1
  type: oob
mac_address_table:
  aging_time: 1300
management_api_http:
  enable_vrfs:
  - name: management
  enable_https: true
ethernet_interfaces:
- name: Ethernet1/1
  peer: ENT-DC2-LEAF1
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF1_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.0/31
- name: Ethernet2/1
  peer: ENT-DC2-LEAF2
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF2_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.4/31
- name: Ethernet3/1
  peer: ENT-DC2-LEAF3
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF3_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.8/31
- name: Ethernet4/1
  peer: ENT-DC2-LEAF4
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF4_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.12/31
- name: Ethernet5/1
  peer: ENT-DC2-LEAF5
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF5_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.16/31
- name: Ethernet6/1
  peer: ENT-DC2-LEAF6
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-LEAF6_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.20/31
- name: Ethernet7/1
  peer: ENT-DC2-BORDER1
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-BORDER1_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.120/31
- name: Ethernet8/1
  peer: ENT-DC2-BORDER2
  peer_interface: Ethernet49/1
  peer_type: l3leaf
  description: P2P_LINK_TO_ENT-DC2-BORDER2_Ethernet49/1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.2.0.124/31
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 10.2.100.1/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.2.100.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
