---
# inventory.yml
all:
  children:
    CVP:
      hosts:
        cvp:
    EnterpriseDC:
      children:
        EnterpriseDC1:
          children:
            EnterpriseDC1Spines:
              hosts:
                ENT-DC1-SPINE1:
                ENT-DC1-SPINE2:
            EnterpriseDC1Leaves:
              children:
                EnterpriseDC1LeafDomain1:
                  hosts:
                    ENT-DC1-LEAF1:
                    ENT-DC1-LEAF2:
                EnterpriseDC1LeafDomain2:
                  hosts:
                    ENT-DC1-LEAF3:
                    ENT-DC1-LEAF4:
                EnterpriseDC1LeafDomain3:
                  hosts:
                    ENT-DC1-LEAF5:
                    ENT-DC1-LEAF6:
                EnterpriseDC1EdgeLeaves:
                  hosts:
                    ENT-DC1-EDGE1:
                    ENT-DC1-EDGE2:
        EnterpriseDC2:
          children:
            EnterpriseDC2Spines:
              hosts:
                ENT-DC2-SPINE1:
                ENT-DC2-SPINE2:
            EnterpriseDC2Leaves:
              children:
                EnterpriseDC2LeafDomain1:
                  hosts:
                    ENT-DC2-LEAF1:
                    ENT-DC2-LEAF2:
                EnterpriseDC2LeafDomain2:
                  hosts:
                    ENT-DC2-LEAF3:
                    ENT-DC2-LEAF4:
                EnterpriseDC2LeafDomain3:
                  hosts:
                    ENT-DC2-LEAF5:
                    ENT-DC2-LEAF6:
                EnterpriseDC2EdgeLeaves:
                  hosts:
                    ENT-DC2-EDGE1:
                    ENT-DC2-EDGE2:
    TenantNetworks:
      children:
        EnterpriseDC1LeafDomain1:
        EnterpriseDC1LeafDomain2:
        EnterpriseDC1LeafDomain3:
        EnterpriseDC1EdgeLeaves:
        EnterpriseDC2LeafDomain1:
        EnterpriseDC2LeafDomain2:
        EnterpriseDC2LeafDomain3:
        EnterpriseDC2EdgeLeaves:
    ConnectedEndpoints:
      children:
        EnterpriseDC1LeafDomain1:
        EnterpriseDC1LeafDomain2:
        EnterpriseDC1LeafDomain3:
        EnterpriseDC1EdgeLeaves:
        EnterpriseDC2LeafDomain1:
        EnterpriseDC2LeafDomain2:
        EnterpriseDC2LeafDomain3:
        EnterpriseDC2EdgeLeaves: