---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: DC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: 'reset local folders for output'
      tags: [build, provision]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags: [build, provision]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, provision]
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cvp
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning
      tags: [provision]
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC_FABRIC'
        configlets_prefix: 'AVD-L3LSV'
        state: present
        cv_collection: v3
