---
- name: Configlet upload management
  hosts: cvp
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: 'upload AVD generated configlets to cloudvision {{inventory_hostname}}'
      tags: [ avd ]
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'inventory/intended/configs'
        file_extension: 'cfg'
        configlets_cvp_prefix: 'none'
        execute_tasks: false
        cv_collection: v3
    - name: 'upload shared configlets to cloudvision {{inventory_hostname}}'
      tags: [ common ]
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'cvp_configlets'
        file_extension: 'txt'
        configlets_cvp_prefix: 'AVD'
        execute_tasks: false
        cv_collection: v3