---
connected_endpoints_keys:
  servers:
    type: server
  firewalls:
    type: firewall
  routers:
    type: router

port_profiles:

  DC1_RACK1_SERVER:
    mode: trunk
    vlans: 10,20,110,111
    spanning_tree_portfast: edge
  DC1_RACK2_SERVER:
    mode: trunk
    vlans: 10,20,110,112
    spanning_tree_portfast: edge
  DC1_RACK3_SERVER:
    mode: trunk
    vlans: 10,20,110,113
    spanning_tree_portfast: edge

# servers
servers:
  ENT-DC1-HOST1:
    rack: DC1_LEAF_DOMAIN_1
    adapters:
      # MLAG dual-homed connection from Et1 to ENT-DC1-LEAF1_Eth1
      #                            from Et2 to ENT-DC1-LEAF2_Eth1
      - endpoint_ports: [ Et1, Et2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ ENT-DC1-LEAF1, ENT-DC1-LEAF2 ]
        profile: DC1_RACK1_SERVER
        port_channel:
          description: PortChannel101
          mode: active
          raw_eos_cli: |-
            sflow enable
  ENT-DC1-HOST2:
    rack: DC1_LEAF_DOMAIN_2
    adapters:
      # MLAG dual-homed connection from Et1 to ENT-DC1-LEAF3_Eth1
      #                            from Et2 to ENT-DC1-LEAF4_Eth1
      - endpoint_ports: [ Et1, Et2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ ENT-DC1-LEAF3, ENT-DC1-LEAF4 ]
        profile: DC1_RACK2_SERVER
        port_channel:
          description: PortChannel101
          mode: active
          raw_eos_cli: |-
            sflow enable
  ENT-DC1-HOST3:
    rack: DC1_LEAF_DOMAIN_3
    adapters:
      # MLAG dual-homed connection from Et1 to ENT-DC1-LEAF5_Eth1
      #                            from Et2 to ENT-DC1-LEAF6_Eth1
      - endpoint_ports: [ Et1, Et2 ]
        switch_ports: [ Ethernet1, Ethernet1 ]
        switches: [ ENT-DC1-LEAF5, ENT-DC1-LEAF6 ]
        profile: DC1_RACK3_SERVER
        port_channel:
          description: PortChannel101
          mode: active
          raw_eos_cli: |-
            sflow enable
