---
# Define Node Type for Group
type: spine

# Spine Switch Definitions
spine:
  defaults:
    platform: cEOSLab
    mgmt_interface: Management1
    bgp_as: 65003
    loopback_ipv4_pool: 10.3.100.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    DC3-SPINE1:
      id: 1
      mgmt_ip: 10.99.99.213/24
    DC3-SPINE2:
      id: 2
      mgmt_ip: 10.99.99.214/24