---
# Define Node Type for Group
type: l3leaf

# Leaf Switch Definitions
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: cEOSLab
    mgmt_interface: Management1
    loopback_ipv4_pool: 10.3.103.0/24
    vtep_loopback_ipv4_pool: 10.3.113.0/24
    uplink_ipv4_pool: 10.3.0.0/20
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    uplink_switches: ['DC3-SPINE1', 'DC3-SPINE2']
    mlag_interfaces: [ Ethernet55/1, Ethernet56/1 ]
    mlag_peer_ipv4_pool: 10.255.255.0/24
    mlag_peer_l3_ipv4_pool: 10.255.254.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: mstp
  node_groups:
    DC3_LEAF_DOMAIN_1:
      bgp_as: 65301
      nodes:
        DC3-LEAF1:
          id: 1
          mgmt_ip: 10.99.99.215/24
          uplink_switch_interfaces: ['Ethernet1/1', 'Ethernet1/1']
          filter:
            tags: [ compute ]
        DC3-LEAF2:
          id: 2
          mgmt_ip: 10.99.99.216/24
          uplink_switch_interfaces: ['Ethernet2/1', 'Ethernet2/1']
          filter:
            tags: [ compute ]
    DC3_LEAF_DOMAIN_2:
      bgp_as: 65302
      nodes:
        DC3-LEAF3:
          id: 3
          mgmt_ip: 10.99.99.217/24
          uplink_switch_interfaces: ['Ethernet3/1', 'Ethernet3/1']
          filter:
            tags: [ compute ]
        DC3-LEAF4:
          id: 4
          mgmt_ip: 10.99.99.218/24
          uplink_switch_interfaces: ['Ethernet4/1', 'Ethernet4/1']
          filter:
            tags: [ compute ]
    DC3_BORDER_LEAVES:
      bgp_as: 65316
      nodes:
        DC3-BORDER1:
          id: 127
          mgmt_ip: 10.99.99.219/24
          uplink_switch_interfaces: ['Ethernet7/1', 'Ethernet7/1']
          filter:
            tags: [ border ]
        DC3-BORDER2:
          id: 128
          mgmt_ip: 10.99.99.220/24
          uplink_switch_interfaces: ['Ethernet8/1', 'Ethernet8/1']
          filter:
            tags: [ border ]