---
# Define Node Type for Group
type: spine

# Spine Switch Definitions
spine:
  defaults:
    platform: cEOSLab
    mgmt_interface: Management1
    bgp_as: 65000
    loopback_ipv4_pool: 10.255.252.0/28
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    DC-SPINE1:
      id: 1
      mgmt_ip: 10.99.99.178/24
    DC-SPINE2:
      id: 2
      mgmt_ip: 10.99.99.179/24